export interface ProfessionData {
  slug: string;
  name: string;
  category: string;
  description: string;
  /** SARS eFiling OFO occupation code(s) used on the ITR12 */
  sarsOccupationCodes: { code: string; title: string }[];
  /** Typical IRP5/IT3(a) source codes this profession encounters */
  irp5SourceCodes: { code: string; description: string }[];
  commonDeductions: { item: string; sarsRef: string }[];
  searchTerms: string[];
}

export const professions: ProfessionData[] = [
  {
    slug: "software-developer",
    name: "Software Developer",
    category: "Technology",
    description: "software developers, programmers, and IT professionals",
    sarsOccupationCodes: [
      { code: "2512", title: "Software Developer" },
      { code: "2514", title: "Applications Programmer" },
      { code: "2511", title: "Systems Analyst" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3616", description: "Independent Contractor" },
      { code: "3606", description: "Overtime" },
    ],
    commonDeductions: [
      { item: "Home office expenses — internet, electricity, dedicated workspace (must be used exclusively for work)", sarsRef: "Section 23(b)" },
      { item: "Computer equipment and peripherals — laptops, monitors, keyboards (depreciation over 3 years)", sarsRef: "Section 11(e), IN 47" },
      { item: "Software licenses and subscriptions — IDE, cloud services, hosting", sarsRef: "Section 11(a)" },
      { item: "Online courses and certifications — Udemy, Coursera, AWS/Azure certs (if directly related to current employment)", sarsRef: "Section 11(a)" },
      { item: "Professional body fees — e.g. IITPSA membership", sarsRef: "Section 11(a)" },
      { item: "Co-working space fees (if no employer-provided office)", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["programmer", "developer", "software engineer", "IT professional", "coder", "web developer"],
  },
  {
    slug: "doctor",
    name: "Doctor",
    category: "Medical",
    description: "doctors, physicians, and medical practitioners",
    sarsOccupationCodes: [
      { code: "2211", title: "General Medical Practitioner" },
      { code: "2212", title: "Specialist Medical Practitioner" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3616", description: "Independent Contractor (locum / private practice)" },
      { code: "3605", description: "Commission" },
    ],
    commonDeductions: [
      { item: "HPCSA annual registration and professional body fees", sarsRef: "Section 11(a)" },
      { item: "Professional indemnity insurance premiums", sarsRef: "Section 11(a)" },
      { item: "Medical equipment and instruments (depreciation applies)", sarsRef: "Section 11(e), IN 47" },
      { item: "Continuing Professional Development (CPD) — courses, conferences, seminars", sarsRef: "Section 11(a)" },
      { item: "Medical journals, textbooks, and reference subscriptions", sarsRef: "Section 11(a)" },
      { item: "Locum travel expenses between facilities (logbook required for vehicle claims)", sarsRef: "Section 8(1)(b)" },
    ],
    searchTerms: ["physician", "GP", "specialist", "medical practitioner", "surgeon"],
  },
  {
    slug: "nurse",
    name: "Nurse",
    category: "Medical",
    description: "nurses, nursing sisters, and healthcare workers",
    sarsOccupationCodes: [
      { code: "2221", title: "Nursing Professional" },
      { code: "2222", title: "Midwife" },
      { code: "3221", title: "Enrolled Nurse" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3606", description: "Overtime" },
      { code: "3616", description: "Independent Contractor (agency / locum)" },
    ],
    commonDeductions: [
      { item: "SANC registration fees (mandatory professional registration)", sarsRef: "Section 11(a)" },
      { item: "Uniform and protective clothing — scrubs, shoes (if not supplied by employer)", sarsRef: "Section 11(a)" },
      { item: "CPD courses, nursing workshops, and further certifications", sarsRef: "Section 11(a)" },
      { item: "Travel between healthcare facilities (logbook required)", sarsRef: "Section 8(1)(b)" },
      { item: "Medical equipment purchased out of pocket — stethoscope, BP monitor", sarsRef: "Section 11(e)" },
      { item: "Professional indemnity insurance", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["nursing sister", "registered nurse", "enrolled nurse", "healthcare worker"],
  },
  {
    slug: "teacher",
    name: "Teacher",
    category: "Education",
    description: "teachers, educators, lecturers, and tutors",
    sarsOccupationCodes: [
      { code: "2341", title: "Primary School Teacher" },
      { code: "2342", title: "Secondary School Teacher" },
      { code: "2310", title: "University/Higher Education Lecturer" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3606", description: "Overtime" },
    ],
    commonDeductions: [
      { item: "SACE registration fees (mandatory for educators)", sarsRef: "Section 11(a)" },
      { item: "Teaching materials and stationery purchased out of pocket", sarsRef: "Section 11(a)" },
      { item: "Further education — courses, diplomas, workshops directly related to teaching role", sarsRef: "Section 11(a)" },
      { item: "Home office for lesson planning and marking (if required by employer, used exclusively)", sarsRef: "Section 23(b)" },
      { item: "Computer and printing expenses used for school work", sarsRef: "Section 11(e)" },
      { item: "Educational software and online teaching tools", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["educator", "lecturer", "tutor", "professor", "school teacher"],
  },
  {
    slug: "accountant",
    name: "Accountant",
    category: "Finance",
    description: "accountants, auditors, bookkeepers, and tax practitioners",
    sarsOccupationCodes: [
      { code: "2411", title: "Accountant" },
      { code: "2412", title: "Financial & Investment Adviser" },
      { code: "3313", title: "Bookkeeper" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3616", description: "Independent Contractor (private practice)" },
      { code: "3617", description: "Director's Remuneration" },
    ],
    commonDeductions: [
      { item: "Professional body fees — SAICA, SAIPA, IRBA, SAIT annual subscriptions", sarsRef: "Section 11(a)" },
      { item: "Accounting software subscriptions — Sage, Xero, QuickBooks, CaseWare", sarsRef: "Section 11(a)" },
      { item: "CPD training, SAICA conferences, technical updates", sarsRef: "Section 11(a)" },
      { item: "Professional indemnity insurance", sarsRef: "Section 11(a)" },
      { item: "Home office expenses (for practitioners with private clients)", sarsRef: "Section 23(b)" },
      { item: "Technical publications, tax handbooks, and research databases", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["CA", "chartered accountant", "auditor", "bookkeeper", "tax practitioner", "CPA"],
  },
  {
    slug: "lawyer",
    name: "Lawyer",
    category: "Legal",
    description: "attorneys, advocates, and legal practitioners",
    sarsOccupationCodes: [
      { code: "2611", title: "Lawyer / Attorney" },
      { code: "2612", title: "Judge" },
      { code: "2619", title: "Legal Professional NEC" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3616", description: "Independent Contractor (own practice / advocate)" },
      { code: "3617", description: "Director's Remuneration" },
    ],
    commonDeductions: [
      { item: "Law Society or Bar Council annual fees and Fidelity Fund contributions", sarsRef: "Section 11(a)" },
      { item: "Legal research subscriptions — LexisNexis, Juta, HeinOnline", sarsRef: "Section 11(a)" },
      { item: "Professional indemnity insurance (mandatory for practising attorneys)", sarsRef: "Section 11(a)" },
      { item: "CPD seminars, legal conferences, and continuing education", sarsRef: "Section 11(a)" },
      { item: "Court attire — advocates' gowns and bibs (replacement)", sarsRef: "Section 11(a)" },
      { item: "Home office and law library expenses (for sole practitioners)", sarsRef: "Section 23(b)" },
    ],
    searchTerms: ["attorney", "advocate", "legal practitioner", "solicitor", "conveyancer"],
  },
  {
    slug: "engineer",
    name: "Engineer",
    category: "Engineering",
    description: "engineers across civil, mechanical, electrical, and other disciplines",
    sarsOccupationCodes: [
      { code: "2142", title: "Civil Engineer" },
      { code: "2144", title: "Mechanical Engineer" },
      { code: "2143", title: "Electrical Engineer" },
      { code: "2149", title: "Engineering Professional NEC" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3616", description: "Independent Contractor (consulting engineer)" },
      { code: "3606", description: "Overtime" },
    ],
    commonDeductions: [
      { item: "ECSA registration and annual professional fees", sarsRef: "Section 11(a)" },
      { item: "Engineering software licenses — AutoCAD, MATLAB, Revit (depreciation if capital)", sarsRef: "Section 11(a) / 11(e)" },
      { item: "Safety equipment and PPE purchased out of pocket", sarsRef: "Section 11(a)" },
      { item: "Site visit travel expenses (logbook required for own vehicle)", sarsRef: "Section 8(1)(b)" },
      { item: "CPD courses, technical conferences, and engineering workshops", sarsRef: "Section 11(a)" },
      { item: "Technical reference books and SANS/SABS standards", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["civil engineer", "mechanical engineer", "electrical engineer", "structural engineer", "ECSA"],
  },
  {
    slug: "freelancer",
    name: "Freelancer",
    category: "Self-Employed",
    description: "freelancers, independent contractors, and gig workers",
    sarsOccupationCodes: [
      { code: "N/A", title: "Varies by trade — select your specific occupation on eFiling" },
    ],
    irp5SourceCodes: [
      { code: "3616", description: "Independent Contractor" },
      { code: "3619", description: "Labour Broker" },
      { code: "3605", description: "Commission" },
    ],
    commonDeductions: [
      { item: "Home office deduction — must be a dedicated room used regularly and exclusively for trade", sarsRef: "Section 23(b)" },
      { item: "Internet, phone, and data expenses (business-use portion only)", sarsRef: "Section 11(a)" },
      { item: "Computer equipment and office furniture (depreciated over useful life)", sarsRef: "Section 11(e), IN 47" },
      { item: "Retirement Annuity contributions — up to 27.5% of taxable income, max R350,000/year", sarsRef: "Section 11(k)" },
      { item: "Accounting fees and invoicing software", sarsRef: "Section 11(a)" },
      { item: "Business insurance, bank charges, and professional subscriptions", sarsRef: "Section 11(a)" },
      { item: "Bad debts written off (clients who didn't pay)", sarsRef: "Section 11(i)" },
    ],
    searchTerms: ["independent contractor", "gig worker", "self-employed", "sole proprietor", "consultant"],
  },
  {
    slug: "sales-representative",
    name: "Sales Representative",
    category: "Sales",
    description: "sales reps, commission earners, and business development professionals",
    sarsOccupationCodes: [
      { code: "2433", title: "Sales Representative (Technical & Medical)" },
      { code: "5242", title: "Sales Demonstrator" },
      { code: "3322", title: "Commercial Sales Representative" },
    ],
    irp5SourceCodes: [
      { code: "3605", description: "Commission" },
      { code: "3601", description: "Salary / Wages (base retainer)" },
      { code: "3602", description: "Annual Payment (bonus)" },
    ],
    commonDeductions: [
      { item: "Vehicle expenses — fuel, maintenance, insurance, depreciation (logbook recommended for actual cost method)", sarsRef: "Section 8(1)(b)" },
      { item: "Cellphone and data costs (business-use portion)", sarsRef: "Section 11(a)" },
      { item: "Client entertainment — meals and venues (must be directly related to trade, keep receipts)", sarsRef: "Section 11(a)" },
      { item: "Home office for admin, reporting, and client management (if >50% commission earner)", sarsRef: "Section 23(b)" },
      { item: "Parking fees and e-toll expenses (business trips only)", sarsRef: "Section 11(a)" },
      { item: "Wear and tear on business equipment — laptop, phone, tablet", sarsRef: "Section 11(e)" },
    ],
    searchTerms: ["sales rep", "commission earner", "BDM", "business development", "account manager"],
  },
  {
    slug: "real-estate-agent",
    name: "Real Estate Agent",
    category: "Property",
    description: "estate agents, property practitioners, and property managers",
    sarsOccupationCodes: [
      { code: "3334", title: "Real Estate Agent" },
      { code: "1439", title: "Property Manager" },
    ],
    irp5SourceCodes: [
      { code: "3605", description: "Commission" },
      { code: "3616", description: "Independent Contractor" },
    ],
    commonDeductions: [
      { item: "Vehicle and fuel expenses — property viewings, show days, client meetings (logbook essential)", sarsRef: "Section 8(1)(b)" },
      { item: "Marketing costs — flyers, signage, online advertising, professional photography", sarsRef: "Section 11(a)" },
      { item: "PPRA (Property Practitioners Regulatory Authority) registration fees", sarsRef: "Section 11(a)" },
      { item: "Cellphone, internet, and data expenses (business portion)", sarsRef: "Section 11(a)" },
      { item: "Home office for admin and client management", sarsRef: "Section 23(b)" },
      { item: "Professional development — NQF courses, compliance training", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["estate agent", "property practitioner", "property manager", "realtor"],
  },
  {
    slug: "graphic-designer",
    name: "Graphic Designer",
    category: "Creative",
    description: "graphic designers, UX/UI designers, and creative professionals",
    sarsOccupationCodes: [
      { code: "2166", title: "Graphic & Multimedia Designer" },
      { code: "2513", title: "Web Developer" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3616", description: "Independent Contractor (freelance design)" },
    ],
    commonDeductions: [
      { item: "Adobe Creative Cloud and design software subscriptions", sarsRef: "Section 11(a)" },
      { item: "High-spec computer, display, and calibration equipment (depreciated)", sarsRef: "Section 11(e), IN 47" },
      { item: "Drawing tablets, peripherals, and ergonomic equipment", sarsRef: "Section 11(e)" },
      { item: "Stock photography, font licenses, and design resources", sarsRef: "Section 11(a)" },
      { item: "Online courses, UX conferences, and design workshops", sarsRef: "Section 11(a)" },
      { item: "Home office and studio expenses (if dedicated space)", sarsRef: "Section 23(b)" },
    ],
    searchTerms: ["designer", "UX designer", "UI designer", "creative", "illustrator", "art director"],
  },
  {
    slug: "consultant",
    name: "Management Consultant",
    category: "Professional Services",
    description: "management consultants, strategy advisors, and business consultants",
    sarsOccupationCodes: [
      { code: "2421", title: "Management & Organisation Analyst" },
      { code: "2422", title: "Policy Administration Professional" },
    ],
    irp5SourceCodes: [
      { code: "3616", description: "Independent Contractor" },
      { code: "3601", description: "Salary / Wages" },
      { code: "3617", description: "Director's Remuneration" },
    ],
    commonDeductions: [
      { item: "Travel expenses — flights, car hire, accommodation for client engagements (receipts required)", sarsRef: "Section 11(a)" },
      { item: "Home office and co-working space fees", sarsRef: "Section 23(b) / 11(a)" },
      { item: "Client entertainment — meals and events directly related to engagements", sarsRef: "Section 11(a)" },
      { item: "Software and research subscriptions — industry reports, analysis tools", sarsRef: "Section 11(a)" },
      { item: "Professional development — MBA tuition (if employer required), short courses", sarsRef: "Section 11(a)" },
      { item: "Professional indemnity insurance and professional body fees", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["management consultant", "strategy consultant", "business advisor", "consulting"],
  },
  {
    slug: "pharmacist",
    name: "Pharmacist",
    category: "Medical",
    description: "pharmacists and pharmaceutical professionals",
    sarsOccupationCodes: [
      { code: "2262", title: "Pharmacist" },
    ],
    irp5SourceCodes: [
      { code: "3601", description: "Salary / Wages" },
      { code: "3616", description: "Independent Contractor (own pharmacy)" },
      { code: "3617", description: "Director's Remuneration" },
    ],
    commonDeductions: [
      { item: "SAPC (South African Pharmacy Council) registration fees", sarsRef: "Section 11(a)" },
      { item: "CPD courses, pharmacy workshops, and clinical updates", sarsRef: "Section 11(a)" },
      { item: "Professional indemnity insurance", sarsRef: "Section 11(a)" },
      { item: "Uniform and lab coat expenses (if not supplied by employer)", sarsRef: "Section 11(a)" },
      { item: "Pharmaceutical reference materials and compounding resources", sarsRef: "Section 11(a)" },
      { item: "Travel between pharmacy locations (logbook required)", sarsRef: "Section 8(1)(b)" },
    ],
    searchTerms: ["pharmacy", "dispensary", "pharmaceutical"],
  },
  {
    slug: "tradesperson",
    name: "Tradesperson",
    category: "Skilled Trades",
    description: "plumbers, electricians, mechanics, and skilled tradespeople",
    sarsOccupationCodes: [
      { code: "7411", title: "Electrician" },
      { code: "7126", title: "Plumber" },
      { code: "7231", title: "Motor Vehicle Mechanic" },
      { code: "7115", title: "Carpenter" },
    ],
    irp5SourceCodes: [
      { code: "3616", description: "Independent Contractor" },
      { code: "3601", description: "Salary / Wages" },
    ],
    commonDeductions: [
      { item: "Tools and equipment purchases (depreciated over useful life per IN 47 rates)", sarsRef: "Section 11(e), IN 47" },
      { item: "Vehicle expenses — travel between job sites (logbook essential)", sarsRef: "Section 8(1)(b)" },
      { item: "Protective clothing and safety gear — PPE, steel-toe boots, hard hats", sarsRef: "Section 11(a)" },
      { item: "Trade-specific training, certifications, and licence renewals", sarsRef: "Section 11(a)" },
      { item: "Cellphone expenses for client coordination (business portion)", sarsRef: "Section 11(a)" },
      { item: "Materials purchased for contract work (not reimbursed by client)", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["plumber", "electrician", "mechanic", "welder", "carpenter", "artisan", "boilermaker"],
  },
  {
    slug: "uber-driver",
    name: "Uber / Ride-Hail Driver",
    category: "Transport",
    description: "Uber drivers, Bolt drivers, and ride-hailing professionals",
    sarsOccupationCodes: [
      { code: "8322", title: "Car, Taxi & Van Driver" },
    ],
    irp5SourceCodes: [
      { code: "3616", description: "Independent Contractor" },
    ],
    commonDeductions: [
      { item: "Vehicle running costs — fuel, maintenance, tyres, insurance (business-use portion per logbook)", sarsRef: "Section 11(a)" },
      { item: "Vehicle finance interest or lease payments (business portion only)", sarsRef: "Section 11(a)" },
      { item: "Depreciation on vehicle (cost limited to R245,056 for 2024/25; over 5 years)", sarsRef: "Section 11(e)" },
      { item: "Cellphone and data plan (business portion)", sarsRef: "Section 11(a)" },
      { item: "Car wash, cleaning, and air freshener expenses", sarsRef: "Section 11(a)" },
      { item: "Parking fees and e-toll charges (business trips)", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["Bolt driver", "ride-hail", "e-hailing", "taxi driver", "minibus"],
  },
  {
    slug: "content-creator",
    name: "Influencer / Content Creator",
    category: "Media & Entertainment",
    description: "social media influencers, YouTubers, TikTokers, podcasters, and digital content creators",
    sarsOccupationCodes: [
      { code: "2642", title: "Journalist" },
      { code: "2654", title: "Film / Stage Director & Producer" },
      { code: "2659", title: "Creative & Performing Artist NEC" },
    ],
    irp5SourceCodes: [
      { code: "3616", description: "Independent Contractor (brand deals, platform income)" },
      { code: "3605", description: "Commission (affiliate income)" },
    ],
    commonDeductions: [
      { item: "Camera, lighting, ring lights, and audio equipment (depreciated over useful life)", sarsRef: "Section 11(e), IN 47" },
      { item: "Editing software subscriptions — Adobe, Final Cut, CapCut Pro, DaVinci Resolve", sarsRef: "Section 11(a)" },
      { item: "Internet, mobile data, and hosting costs (business portion)", sarsRef: "Section 11(a)" },
      { item: "Home studio and dedicated content creation space", sarsRef: "Section 23(b)" },
      { item: "Props, wardrobe, set materials, and production costs (if solely for content)", sarsRef: "Section 11(a)" },
      { item: "Travel for brand collaborations, events, and shoots (if related to income production)", sarsRef: "Section 11(a)" },
      { item: "Social media management tools — Later, Hootsuite, Canva Pro", sarsRef: "Section 11(a)" },
      { item: "Agent/manager commissions and booking fees", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["YouTuber", "influencer", "podcaster", "streamer", "blogger", "vlogger", "TikToker", "social media creator", "Instagram influencer"],
  },
  {
    slug: "tech-contractor",
    name: "Tech Contractor",
    category: "Technology",
    description: "independent IT contractors, dev contractors, and technology consultants working on contract",
    sarsOccupationCodes: [
      { code: "2512", title: "Software Developer" },
      { code: "2519", title: "ICT Professional NEC" },
      { code: "2521", title: "Database Designer & Administrator" },
      { code: "2523", title: "Computer Network Professional" },
    ],
    irp5SourceCodes: [
      { code: "3616", description: "Independent Contractor" },
      { code: "3601", description: "Salary / Wages (if on payroll via agency)" },
    ],
    commonDeductions: [
      { item: "Home office expenses — internet, electricity, dedicated workspace (must be used exclusively for work)", sarsRef: "Section 23(b)" },
      { item: "Computer equipment — laptops, monitors, docking stations, peripherals (depreciation over 3 years)", sarsRef: "Section 11(e), IN 47" },
      { item: "Software licenses and cloud subscriptions — IDE, GitHub, AWS, Azure, hosting", sarsRef: "Section 11(a)" },
      { item: "Retirement Annuity contributions — critical for contractors with no employer pension (up to 27.5% of taxable income, max R350,000)", sarsRef: "Section 11(k)" },
      { item: "Professional indemnity and business insurance", sarsRef: "Section 11(a)" },
      { item: "Travel to client sites — fuel, e-tolls, parking, flights (logbook if using own vehicle)", sarsRef: "Section 8(1)(b) / 11(a)" },
      { item: "Accounting, invoicing software, and tax preparation fees", sarsRef: "Section 11(a)" },
      { item: "Co-working space fees and meeting room hire", sarsRef: "Section 11(a)" },
      { item: "Technical courses, certifications (AWS, Azure, Kubernetes), and conference attendance", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["IT contractor", "dev contractor", "technology consultant", "independent developer", "contract programmer", "freelance developer", "software contractor"],
  },
  {
    slug: "musician",
    name: "Musician",
    category: "Arts & Entertainment",
    description: "musicians, session players, music producers, DJs, and performing artists",
    sarsOccupationCodes: [
      { code: "2652", title: "Musician, Singer & Composer" },
      { code: "2653", title: "Dancer & Choreographer" },
      { code: "2659", title: "Creative & Performing Artist NEC" },
    ],
    irp5SourceCodes: [
      { code: "3616", description: "Independent Contractor (gigs, session work, production)" },
      { code: "3601", description: "Salary / Wages (if employed by orchestra, venue, etc.)" },
    ],
    commonDeductions: [
      { item: "Musical instruments — purchase price depreciated over useful life (guitars, keyboards, drums, etc.)", sarsRef: "Section 11(e), IN 47" },
      { item: "Recording and production equipment — audio interface, microphones, monitors, DAW hardware", sarsRef: "Section 11(e), IN 47" },
      { item: "Music software and subscriptions — Logic Pro, Ableton, Pro Tools, Spotify for Artists, DistroKid", sarsRef: "Section 11(a)" },
      { item: "Home studio setup — soundproofing, acoustic treatment, dedicated room", sarsRef: "Section 23(b)" },
      { item: "Travel to gigs, recording sessions, and rehearsals (logbook if own vehicle)", sarsRef: "Section 8(1)(b) / 11(a)" },
      { item: "Agent/manager commissions and booking agency fees", sarsRef: "Section 11(a)" },
      { item: "Marketing and promotion — website, social media ads, press kits, music videos", sarsRef: "Section 11(a)" },
      { item: "Instrument maintenance — repairs, strings, accessories, tuning", sarsRef: "Section 11(a)" },
      { item: "SAMRO, CAPASSO, and other music rights organisation fees", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["session musician", "music producer", "DJ", "singer", "performer", "band member", "sound engineer", "recording artist", "rapper", "vocalist"],
  },
  {
    slug: "artist",
    name: "Visual Artist",
    category: "Arts & Entertainment",
    description: "visual artists, fine artists, illustrators, sculptors, and photographers",
    sarsOccupationCodes: [
      { code: "2651", title: "Visual Artist" },
      { code: "3431", title: "Photographer" },
      { code: "2166", title: "Graphic & Multimedia Designer" },
    ],
    irp5SourceCodes: [
      { code: "3616", description: "Independent Contractor (commissions, gallery sales)" },
      { code: "3601", description: "Salary / Wages (if employed by studio, agency, etc.)" },
    ],
    commonDeductions: [
      { item: "Art supplies and materials — paint, canvas, clay, ink, paper, printing materials", sarsRef: "Section 11(a)" },
      { item: "Camera and photography equipment (depreciated over useful life)", sarsRef: "Section 11(e), IN 47" },
      { item: "Digital tools — drawing tablet, stylus, high-spec computer, calibration monitor", sarsRef: "Section 11(e), IN 47" },
      { item: "Studio or workspace rental (or home studio under Section 23(b))", sarsRef: "Section 23(b) / 11(a)" },
      { item: "Software subscriptions — Adobe Creative Suite, Procreate, Lightroom", sarsRef: "Section 11(a)" },
      { item: "Exhibition costs — gallery fees, framing, shipping, installation", sarsRef: "Section 11(a)" },
      { item: "Portfolio website, hosting, and online gallery platform fees", sarsRef: "Section 11(a)" },
      { item: "Travel to exhibitions, commissions, client meetings, and art fairs", sarsRef: "Section 11(a)" },
      { item: "Art courses, workshops, and residency application fees (if related to current trade)", sarsRef: "Section 11(a)" },
    ],
    searchTerms: ["fine artist", "illustrator", "sculptor", "photographer", "painter", "printmaker", "visual creative", "art photographer", "portrait photographer"],
  },
];

export function getProfessionBySlug(slug: string): ProfessionData | undefined {
  return professions.find((p) => p.slug === slug);
}
